# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d9fbb29262b2aa8e34856cce6790db9788e66e09fd33f4991fd2b0f0901bb66e04ad04c5ecce391139dc8cbff50acf8f4f4bc0069159dec59e1de87a0ee3fee

test:
  secret_key_base: 4b844329fe8bb39630a9037444890b27752818345ccdd30a9303b4b2590edb71034d6289fea690a01465406dbde8d613c0fc907ea13f21fbb64c5bb2f1b7a9c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
